<a href="https://colab.research.google.com/github/ian-njenga/AI-FOR-SCIENCE-AND-ENGINEERING/blob/Week-3-Assignment-%7C-Designing-Your-Machine-Learning-Workflow/Week_3_Assignment_%7C_Designing_Your_Machine_Learning_Workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Week 3 Assignment | Designing Your Machine Learning Workflow

Engineering problem to be analyzed: analysing the flood risk given expected population and urbanisation rates

In [ ]:
!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Collecting datasets
  Downloading datasets-5.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Collecting pyarrow>=24.0.0 (from datasets)
  Downloading pyarrow-25.0.1-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.7.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (4.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.25.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-5.1.0-py3-none-any.whl (604 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 604.4/604.4 kB 9.2 MB/s eta 0:00:00
Downloading pyarrow-25.0.1-cp313-cp313-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 11.5 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 23.0.1
    Uninstalling pyarrow-23.0.1:
      Successfully uninstalled pyarrow-23.0.1
  Attempting uninstall: datasets
    Found existing installation: datasets 4.8.5
    Uninstalling datasets-4.8.5:
      Successfully uninstalled datasets-4.8.5
Successfully installed datasets-5.1.0 pyarrow-25.0.1

In [2]:
from datasets import load_dataset

In [3]:
pop_dataset = load_dataset('electricsheepafrica/africa-population-kenya')
demo_dataset = load_dataset('electricsheepafrica/africa-demographics-kenya')
climate_dataset = load_dataset('electricsheepafrica/africa-world-bank-climate-change-indicators-for-kenya')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/5.70k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.61kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 5.81kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/39 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/10 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 22.9kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 8.94kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1284 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/321 [00:00<?, ? examples/s]

In [5]:
print(pop_dataset)
print(demo_dataset)
print(climate_dataset)

DatasetDict({
    train: Dataset({
        features: ['year', 'country', 'iso', 'disaster_group', 'disaster_subroup', 'disaster_type', 'disaster_subtype', 'total_events', 'total_affected', 'total_deaths', 'cpi', 'esa_source', 'esa_processed'],
        num_rows: 39
    })
    test: Dataset({
        features: ['year', 'country', 'iso', 'disaster_group', 'disaster_subroup', 'disaster_type', 'disaster_subtype', 'total_events', 'total_affected', 'total_deaths', 'cpi', 'esa_source', 'esa_processed'],
        num_rows: 10
    })
})
DatasetDict({
    train: Dataset({
        features: ['adm2_pcode', 'adm_pcode', 'female_pop', 'children_u5', 'female_u5', 'elderly', 'pop_u15', 'female_u15', 'esa_source', 'esa_processed'],
        num_rows: 232
    })
    test: Dataset({
        features: ['adm2_pcode', 'adm_pcode', 'female_pop', 'children_u5', 'female_u5', 'elderly', 'pop_u15', 'female_u15', 'esa_source', 'esa_processed'],
        num_rows: 58
    })
})
DatasetDict({
    train: Dataset({
        features: ['country_name', 'country_iso3', 'year', 'indicator_name', 'indicator_code', 'value', 'esa_source', 'esa_processed'],
        num_rows: 1284
    })
    test: Dataset({
        features: ['country_name', 'country_iso3', 'year', 'indicator_name', 'indicator_code', 'value', 'esa_source', 'esa_processed'],
        num_rows: 321
    })
})

In [6]:
import pandas as pd
import numpy as np

In [11]:
population_df_train = pop_dataset['train'].to_pandas()
demographics_df_train = demo_dataset['train'].to_pandas()
climate_df_train = climate_dataset['train'].to_pandas()

population_df_test= pop_dataset['train'].to_pandas()
demographics_df_test = demo_dataset['train'].to_pandas()
climate_df_test = climate_dataset['train'].to_pandas()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              38 non-null     float64
 1   country           39 non-null     object
 2   iso               39 non-null     object
 3   disaster_group    39 non-null     object
 4   disaster_subroup  39 non-null     object
 5   disaster_type     39 non-null     object
 6   disaster_subtype  39 non-null     object
 7   total_events      38 non-null     float64
 8   total_affected    34 non-null     float64
 9   total_deaths      31 non-null     float64
 10  cpi               36 non-null     float64
 11  esa_source        39 non-null     object
 12  esa_processed     39 non-null     object
dtypes: float64(5), object(8)
memory usage: 4.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   adm2_pcode     232 non-null    object
 1   adm_pcode      232 non-null    object
 2   female_pop     232 non-null    int64
 3   children_u5    232 non-null    int64
 4   female_u5      232 non-null    int64
 5   elderly        232 non-null    int64
 6   pop_u15        232 non-null    int64
 7   female_u15     232 non-null    int64
 8   esa_source     232 non-null    object
 9   esa_processed  232 non-null    object
dtypes: int64(6), object(4)
memory usage: 18.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    1284 non-null   object
 1   country_iso3    1284 non-null   object
 2   year            1284 non-null   int64
 3   indicator_name  1284 non-null   object
 4   indicator_code  1284 non-null   object
 5   value           1284 non-null   float64
 6   esa_source      1284 non-null   object
 7   esa_processed   1284 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 80.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              38 non-null     float64
 1   country           39 non-null     object
 2   iso               39 non-null     object
 3   disaster_group    39 non-null     object
 4   disaster_subroup  39 non-null     object
 5   disaster_type     39 non-null     object
 6   disaster_subtype  39 non-null     object
 7   total_events      38 non-null     float64
 8   total_affected    34 non-null     float64
 9   total_deaths      31 non-null     float64
 10  cpi               36 non-null     float64
 11  esa_source        39 non-null     object
 12  esa_processed     39 non-null     object
dtypes: float64(5), object(8)
memory usage: 4.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   adm2_pcode     232 non-null    object
 1   adm_pcode      232 non-null    object
 2   female_pop     232 non-null    int64
 3   children_u5    232 non-null    int64
 4   female_u5      232 non-null    int64
 5   elderly        232 non-null    int64
 6   pop_u15        232 non-null    int64
 7   female_u15     232 non-null    int64
 8   esa_source     232 non-null    object
 9   esa_processed  232 non-null    object
dtypes: int64(6), object(4)
memory usage: 18.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    1284 non-null   object
 1   country_iso3    1284 non-null   object
 2   year            1284 non-null   int64
 3   indicator_name  1284 non-null   object
 4   indicator_code  1284 non-null   object
 5   value           1284 non-null   float64
 6   esa_source      1284 non-null   object
 7   esa_processed   1284 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 80.4+ KB

              year         value
count  1284.000000  1.284000e+03
mean   1998.132399  3.703812e+07
std      16.914150  3.580071e+08
min    1960.000000 -7.420000e+06
25%    1987.000000  6.323580e+00
50%    2000.000000  2.876083e+01
75%    2012.000000  4.717163e+02
max    2025.000000  5.662350e+09

In [12]:
population_df_train.info()
demographics_df_train.info()
climate_df_train.info()

population_df_test.info()
demographics_df_test.info()
climate_df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              38 non-null     float64
 1   country           39 non-null     object
 2   iso               39 non-null     object
 3   disaster_group    39 non-null     object
 4   disaster_subroup  39 non-null     object
 5   disaster_type     39 non-null     object
 6   disaster_subtype  39 non-null     object
 7   total_events      38 non-null     float64
 8   total_affected    34 non-null     float64
 9   total_deaths      31 non-null     float64
 10  cpi               36 non-null     float64
 11  esa_source        39 non-null     object
 12  esa_processed     39 non-null     object
dtypes: float64(5), object(8)
memory usage: 4.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   adm2_pcode     232 non-null    object
 1   adm_pcode      232 non-null    object
 2   female_pop     232 non-null    int64
 3   children_u5    232 non-null    int64
 4   female_u5      232 non-null    int64
 5   elderly        232 non-null    int64
 6   pop_u15        232 non-null    int64
 7   female_u15     232 non-null    int64
 8   esa_source     232 non-null    object
 9   esa_processed  232 non-null    object
dtypes: int64(6), object(4)
memory usage: 18.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    1284 non-null   object
 1   country_iso3    1284 non-null   object
 2   year            1284 non-null   int64
 3   indicator_name  1284 non-null   object
 4   indicator_code  1284 non-null   object
 5   value           1284 non-null   float64
 6   esa_source      1284 non-null   object
 7   esa_processed   1284 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 80.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              38 non-null     float64
 1   country           39 non-null     object
 2   iso               39 non-null     object
 3   disaster_group    39 non-null     object
 4   disaster_subroup  39 non-null     object
 5   disaster_type     39 non-null     object
 6   disaster_subtype  39 non-null     object
 7   total_events      38 non-null     float64
 8   total_affected    34 non-null     float64
 9   total_deaths      31 non-null     float64
 10  cpi               36 non-null     float64
 11  esa_source        39 non-null     object
 12  esa_processed     39 non-null     object
dtypes: float64(5), object(8)
memory usage: 4.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   adm2_pcode     232 non-null    object
 1   adm_pcode      232 non-null    object
 2   female_pop     232 non-null    int64
 3   children_u5    232 non-null    int64
 4   female_u5      232 non-null    int64
 5   elderly        232 non-null    int64
 6   pop_u15        232 non-null    int64
 7   female_u15     232 non-null    int64
 8   esa_source     232 non-null    object
 9   esa_processed  232 non-null    object
dtypes: int64(6), object(4)
memory usage: 18.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    1284 non-null   object
 1   country_iso3    1284 non-null   object
 2   year            1284 non-null   int64
 3   indicator_name  1284 non-null   object
 4   indicator_code  1284 non-null   object
 5   value           1284 non-null   float64
 6   esa_source      1284 non-null   object
 7   esa_processed   1284 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 80.4+ KB

In [13]:
population_df_train.describe()
demographics_df_train.describe()
climate_df_train.describe()

population_df_test.describe()
demographics_df_test.describe()
climate_df_test.describe()

              year         value
count  1284.000000  1.284000e+03
mean   1998.132399  3.703812e+07
std      16.914150  3.580071e+08
min    1960.000000 -7.420000e+06
25%    1987.000000  6.323580e+00
50%    2000.000000  2.876083e+01
75%    2012.000000  4.717163e+02
max    2025.000000  5.662350e+09

In [18]:
pd.set_option('display.max_columns', None)

In [19]:
population_df_train.head()

,year,country,iso,disaster_group,disaster_subroup,disaster_type,disaster_subtype,total_events,total_affected,total_deaths,cpi,esa_source,esa_processed
0,2006.0,Kenya,KEN,Natural,Hydrological,Flood,Riverine flood,4.0,783300.0,212.0,64.264832,HDX,2026-04-29
1,2003.0,Kenya,KEN,Natural,Hydrological,Flood,Riverine flood,2.0,60300.0,40.0,58.643553,HDX,2026-04-29
2,2018.0,Kenya,KEN,Natural,Hydrological,Flood,Flood (General),3.0,211188.0,134.0,80.049596,HDX,2026-04-29
3,2004.0,Kenya,KEN,Natural,Hydrological,Flood,Riverine flood,1.0,10000.0,50.0,60.213580,HDX,2026-04-29
4,2002.0,Kenya,KEN,Natural,Hydrological,Mass movement (wet),Landslide (wet),1.0,NaN,16.0,57.341840,HDX,2026-04-29

In [20]:
demographics_df_train.head()

,adm2_pcode,adm_pcode,female_pop,children_u5,female_u5,elderly,pop_u15,female_u15,esa_source,esa_processed
0,KE007028,KE007028,88717,24668,11656,3918,80391,37366,HDX,2026-04-27
1,KE020102,KE020102,77464,14875,7424,6504,45236,22797,HDX,2026-04-27
2,KE018091,KE018091,35269,8478,4172,2703,26145,12948,HDX,2026-04-27
3,KE019094,KE019094,46873,8636,4228,5190,26642,13329,HDX,2026-04-27
4,KE024131,KE024131,116618,39812,19927,3785,119182,58476,HDX,2026-04-27

In [21]:
climate_df_train.head()

,country_name,country_iso3,year,indicator_name,indicator_code,value,esa_source,esa_processed
0,Kenya,KEN,1996,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,5.150000e+08,HDX,2026-04-09
1,Kenya,KEN,2014,"Annual freshwater withdrawals, total (billion ...",ER.H2O.FWTL.K3,3.219600e+00,HDX,2026-04-09
2,Kenya,KEN,2004,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0.000000e+00,HDX,2026-04-09
3,Kenya,KEN,2011,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,3.094711e+00,HDX,2026-04-09
4,Kenya,KEN,1991,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,5.040000e+08,HDX,2026-04-09

In [22]:
for i, col in enumerate(population_df_train.columns):
    print(i, col)

0 year
1 country
2 iso
3 disaster_group
4 disaster_subroup
5 disaster_type
6 disaster_subtype
7 total_events
8 total_affected
9 total_deaths
10 cpi
11 esa_source
12 esa_processed

In [23]:
for i, col in enumerate(climate_df_train.columns):
    print(i, col)

0 country_name
1 country_iso3
2 year
3 indicator_name
4 indicator_code
5 value
6 esa_source
7 esa_processed

In [25]:
for i, col in enumerate(demographics_df_train.columns):
    print(i, col)

0 adm2_pcode
1 adm_pcode
2 female_pop
3 children_u5
4 female_u5
5 elderly
6 pop_u15
7 female_u15
8 esa_source
9 esa_processed